### ISSUE TITLE
Obtaining API username and pw 

### ISSUE THREAD

**Issue by TheCamFreak** [konradknitter/homebridge-philips-android-tv#17]
Hi, 
I cant obtain username and password. 
Output hangs for a quite while and then gives this:
Starting pairing request
Traceback (most recent call last):
  File "philips.py", line 140, in <module>
    main()
  File "philips.py", line 90, in main
    pair(config)
  File "philips.py", line 41, in pair
    r = requests.post("https://" + config['address'] + ":1926/6/pair/request", json=data, verify=False)
  File "/home/pi/.local/lib/python2.7/site-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/pi/.local/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/pi/.local/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pi/.local/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/home/pi/.local/lib/python2.7/site-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))

I have tried to use python 3 (3.7.3) and the output is:
python3 ./philips.py --host 192.168.0.248 pair
Traceback (most recent call last):
  File "./philips.py", line 9, in <module>
    from Crypto.Hash import SHA, HMAC
ModuleNotFoundError: No module named 'Crypto'

I have tried to add crypto modules, error persists. 
I have tried to open the website with the TV IP and can't reach it. IP address is correct for sure. 
Is there any way to fix this issue ?

**Comment by Staubgeborener** [comment]
Check with `pip -V` / `pip3 -V` that you have the correct version, you will need `pip3`.
After that run `pip3 install -r requirements.txt` to automatically install the dependencies.
Last step: ` python3 ./philips.py --host 192.168.0.248 pair`

The code for `philips.py` is not related to this project, so next time maybe ask [here](https://github.com/suborb/philips_android_tv/issues).
