### ISSUE TITLE
PlayPause button works as Play only

### ISSUE THREAD

**Issue by valaz** [konradknitter/homebridge-philips-android-tv#2]
**PlayPause button works as Play only**
Seems PlayPause action doesn't work for my TV (50PUS7303). It works as Play everytime.
I also have separate Play and Pause buttons on my physical TV control.
Is there any way to workaround it by passing play and pause actions alternately?

**To Reproduce:**
During video/audio playback, play-pause button can't pause playback.
But when video/audio is paused, that button starts playback successfully.

**Plugin Config:**

```json
        {
            "accessory": "PhilipsAndroidTV",
            "name": "TV",
            "ip": "192.168.1.***",
            "macAddress": "**:**:**:**:**:**",
            "apiUser": "****",
            "apiPass": "***************",
            "apps": [
                "YouTube",
                "Spotify",
                "TV"
            ]
        }
```

**Environment:**

* **Plugin Version**: 0.2.0
* **Homebridge Version**:  1.2.3
* **Node.js Version**:  12.8.4
* **NPM Version**: 6.14.6
* **Operating System**: Ubuntu

P.S. Thank you for such a great plugin. I'm happy to use it with my Philips 50PUS7303

**Comment by konradknitter** [comment]
Hi,

thanks for reporting.

Play Pause button is being send as PlayPause to TV.

```
} else if (remoteKey === hap.Characteristic.RemoteKey.PLAY_PAUSE) {
            request_body.key = 'PlayPause';
} 
```

TV have also option for explicit Play and Pause, so I will make alternating way as configurable workaround in next release to support this use case.
Could you please provide me information from 
http://tvip:1925/system about your TV API?

api_version":{"Major":6,"Minor":?,"Patch":0}

Maybe it depends on that

**Comment by konradknitter** [comment]
Added under config flag.

`       "alternativePlayPause": true`

I will publish it soon (with issue #3 and other I've noticed in yesterday drop)

**Comment by konradknitter** [comment]
Delivered as part of 0.2.2 drop

**Comment by valaz** [comment]
@konradknitter thank you for workaround config.

My system:
`"api_version":{"Major":6,"Minor":1,"Patch":0}`

But I'm getting this strange error after update to 0.2.2
```
[11/4/2020, 12:30:48 PM] TypeError: Cannot read property 'name' of undefined
    at PhilipsAndroidTvAccessory.<anonymous> (/usr/lib/node_modules/homebridge-philips-android-tv/src/index.ts:190:90)
    at Request.self.callback (/usr/lib/node_modules/homebridge-philips-android-tv/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-philips-android-tv/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-philips-android-tv/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[11/4/2020, 12:30:48 PM] Got SIGTERM, shutting down Homebridge...
```

Do you know how to fix it?

**Comment by konradknitter** [comment]
Looks that your structure of "activities/tv" is different than mine.
I will add logs and add safe checks to workaround it for now, please bring me later updated logs as this will disable showing proper TV channel.

**Comment by konradknitter** [comment]
Published as 0.2.3.

**Comment by valaz** [comment]
Now it's working. Play-Pause as expected with alternative config. Volume control - also awesome.
Thank you a lot.

My logs: 
```
[11/4/2020, 1:19:54 PM] [TV] getCurrentActivity: unknown activities/tv structure: {}
[11/4/2020, 1:19:54 PM] [TV] getCurrentActivity: unknown activities/tv structure: {}
[11/4/2020, 1:19:54 PM] [TV] getCurrentActivity: unknown activities/tv structure: {}
[11/4/2020, 1:19:54 PM] [TV] getCurrentActivity: unknown activities/tv structure: {}
[11/4/2020, 1:19:54 PM] [TV] getCurrentActivity: unknown activities/tv structure: {}
[11/4/2020, 1:19:58 PM] [TV] getCurrentActivity: unknown activities/tv structure: {}
[11/4/2020, 1:19:58 PM] [TV] getCurrentActivity: unknown activities/tv structure: {}
[11/4/2020, 1:19:58 PM] [TV] getCurrentActivity: unknown activities/tv structure: {}
[11/4/2020, 1:19:58 PM] [TV] getCurrentActivity: unknown activities/tv structure: {}
[11/4/2020, 1:19:58 PM] [TV] getCurrentActivity: unknown activities/tv structure: {}
```

I can invoke any curl command what you say - just give me a command :)

**Comment by konradknitter** [comment]
Again, great to hear that!

I don't know any alternative documented option.

Response on 6.1 differs from one on 6.2, 6.4 versions:
https://github.com/eslavnov/pylips/wiki/Activities-TV-(GET)

That means we can't show channel playing. :(
I will disable this warning on 6.1 TVs in next version.

How about apps? Can you see open app name properly propagated to Home app?

As we get to this lines of code, TV said App open is either "TV" or "NA". So I believe it should, when opening Youtube show Youtube.

**Comment by valaz** [comment]
Apps/Inputs selector works as expected. 
I can switch apps without any issue from Home app.

**Comment by konradknitter** [comment]
Log limited to once per startup in 0.2.4, as seems it's not related to any API version. Do we have any other issue left here?

**Comment by eRJe79** [comment]
With current version 0.2.4 my log is still filling up with

```

[11/7/2020, 19:19:58] [Philips TV] getCurrentActivity: unknown activities/tv structure: {}
[11/7/2020, 19:20:08] [Philips TV] getCurrentActivity: unknown activities/tv structure: {}
[11/7/2020, 19:20:08] [Philips TV] getCurrentActivity: unknown activities/tv structure: {}
[11/7/2020, 19:20:08] [Philips TV] getCurrentActivity: unknown activities/tv structure: {}
[11/7/2020, 19:20:18] [Philips TV] getCurrentActivity: unknown activities/tv structure: {}
[11/7/2020, 19:20:18] [Philips TV] getCurrentActivity: unknown activities/tv structure: {}
[11/7/2020, 19:20:18] [Philips TV] getCurrentActivity: unknown activities/tv structure: {}
[11/7/2020, 19:20:28] [Philips TV] getCurrentActivity: unknown activities/tv structure: {}
[11/7/2020, 19:20:28] [Philips TV] getCurrentActivity: unknown activities/tv structure: {}
[11/7/2020, 19:20:28] [Philips TV] getCurrentActivity: unknown activities/tv structure: {}
```
API v6.4.0

**Comment by valaz** [comment]
> Log limited to once per startup in 0.2.4, as seems it's not related to any API version. Do we have any other issue left here?

PlayPause fixed. So let's close this issue
