### ISSUE TITLE
No accessories and errors in the log

### ISSUE THREAD

**Issue by Francis2b** [konradknitter/homebridge-philips-android-tv#24]
Hi,

Just finished installing the plugin with the Philips API credentials and finish completing the settings ans I can't manage to have accessories and here is my log.

 Any idea what's wrong?

> [2/20/2021, 11:32:45 PM] Homebridge v1.2.4 is running on port 51848.
[2/20/2021, 11:32:46 PM] [TV] {
  component: { packageName: 'com.google.android.tvlauncher', className: 'NA' }
}
[2/20/2021, 11:32:46 PM] [TV] {
  channel: { ccid: 27, preset: '7', name: 'Arte' },
  channelList: { id: 'allter', version: '1' }
}
[2/20/2021, 11:32:46 PM] [TV] Startup Phase #2 - Fetching information about channels from TV
[2/20/2021, 11:32:46 PM] [TV] Startup Phase #2.5 - Fetching information about channels from TV
(node:1379) UnhandledPromiseRejectionWarning: Error: Cannot add a Service with the same UUID '000000D9-0000-1000-8000-0026BB765291' and subtype 'CANAL+' as another Service in this Accessory.
    at Accessory._this.addService (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:284:17)
    at PlatformAccessory.addService (/usr/lib/node_modules/homebridge/src/platformAccessory.ts:93:41)
    at PhilipsAndroidTvAccessory.addChannel (/usr/lib/node_modules/homebridge-philips-android-tv/src/index.ts:339:26)
    at PhilipsAndroidTvAccessory.setupChannelsInputs (/usr/lib/node_modules/homebridge-philips-android-tv/src/index.ts:364:26)
    at /usr/lib/node_modules/homebridge-philips-android-tv/src/index.ts:156:22
    at new Promise (<anonymous>)
    at /usr/lib/node_modules/homebridge-philips-android-tv/src/index.ts:154:20
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:1379) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1379) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by baschte** [comment]
Same here. Can't add and find my TV in my HomeKit app.

**Comment by schmargi91** [comment]
Same here, get Error: 

> [3/14/2021, 11:54:57 PM] [FernseherTV] Startup Phase #2.5 - Fetching information about channels from TV
(node:1702) UnhandledPromiseRejectionWarning: Error: Cannot add a Service with the same UUID '000000D9-0000-1000-8000-0026BB765291' and subtype '.' as another Service in this Accessory.
    at Accessory.addService (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:447:17)
    at PlatformAccessory.addService (/usr/local/lib/node_modules/homebridge/src/platformAccessory.ts:93:41)
    at PhilipsAndroidTvAccessory.addChannel (/homebridge/node_modules/homebridge-philips-android-tv/src/index.ts:339:26)
    at PhilipsAndroidTvAccessory.setupChannelsInputs (/homebridge/node_modules/homebridge-philips-android-tv/src/index.ts:364:26)
    at /homebridge/node_modules/homebridge-philips-android-tv/src/index.ts:156:22
    at new Promise (<anonymous>)
    at /homebridge/node_modules/homebridge-philips-android-tv/src/index.ts:154:20
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)

**Comment by konradknitter** [comment]
Please check new version of plug-in. If issue still exists.
UUID should be no generated randomly.
