### ISSUE TITLE
No access to TV API anymore

### ISSUE THREAD

**Issue by GuitarHer01** [konradknitter/homebridge-philips-android-tv#27]
I think starting with the last update of my TV, there is no connection anymore to the TV.

The homebridge log shows:
```
[23-3-2021 15:50:32] [TV] PhilipsTV [192.168.1.100]: Tried to make TV responsive over 100 requests and failed. Please double check configuration.
[23-3-2021 15:50:32] [TV] Startup Phase #2 - Fetching information about channels from TV
[23-3-2021 15:50:33] [TV] Startup Phase #2.5 - Fetching information about channels from TV
[23-3-2021 15:50:33] [TV] Startup Phase #3 - Fetching information about application from TV
[23-3-2021 15:50:35] [TV] fetchPossibleApplications - can not reach TV API. Inputs won't be visible in HomeKit. Please restart homebridge when TV will be online to recover inputs.
[23-3-2021 15:50:35] [TV] Startup Completed - Publishing External HomeKit Accessory.Accessory will not be automaticly added to Home - it has to be manually added in Home app.
```
This has worked fine before however.

The TV is a Philips 58PUS8535
Software Upgrade
version: 101.001.250.003
15 march 2021

Any idea's on this?

**Comment by ortoberi** [comment]
After FW/SW upgrade of my Philips TV (805 a few days a go), I get this:
[23/03/2021, 20:12:54] SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at PhilipsAndroidTvAccessory.<anonymous> (/usr/local/lib/node_modules/homebridge-philips-android-tv/src/index.ts:507:37)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-philips-android-tv/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-philips-android-tv/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-philips-android-tv/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
[23/03/2021, 20:12:54] SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at PhilipsAndroidTvAccessory.<anonymous> (/usr/local/lib/node_modules/homebridge-philips-android-tv/src/index.ts:471:37)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-philips-android-tv/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-philips-android-tv/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-philips-android-tv/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)

and constant rebooting of my Homebridge. Currently, I disabled your plugin, that I can use Homebridge for other devices.

**Comment by try-and-error-and-repeat** [comment]
The problem is that with the last firmware update your apiuser and apipassword are invalid. try to pair again with the script and change the Homebridge config and it should work again

**Comment by ortoberi** [comment]
> The problem is that with the last firmware update your apiuser and apipassword are invalid. try to pair again with the script and change the Homebridge config and it should work again

I didn't know that updates can change the API user and password. I solved this with the phyton script. Thx.

**Comment by GuitarHer01** [comment]
I used the Python script to get the new username and password and it works again indeed. 
Thx!
