### ISSUE TITLE
Issue after update homebridge to 1.3.4

### ISSUE THREAD

**Issue by Tabek-pl** [konradknitter/homebridge-philips-android-tv#29]
After update homebridge to 1.3.4 plugin crash whole homebridge instance.

[2021-4-9 9:24:58] SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at PhilipsAndroidTvAccessory.<anonymous> (/usr/lib/node_modules/homebridge-philips-android-tv/src/index.ts:507:37)
    at Request.self.callback (/usr/lib/node_modules/homebridge-philips-android-tv/node_modules/request/request.js:185:22)
    at Request.emit (events.js:223:5)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-philips-android-tv/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:223:5)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-philips-android-tv/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:312:28)
    at IncomingMessage.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)
[2021-4-9 9:24:58] Got SIGTERM, shutting down Homebridge...

{
            "name": "TV",
            "ip": "192.168.1.55",
            "macAddress": "F8:4F:AD:95:09:4B",
            "apiUser": "apiUser",
            "apiPass": "apiPass",
            "alternativePlayPause": false,
            "dedicatedMuteSwitch": false,
            "dedicatedVolumeLightbulb": false,
            "printConfiguredApps": false,
            "registerAsDefaultAccessory": false,
            "channels": {
                "useFavorites": false,
                "favoriteListId": "1",
                "includeAll": false
            },
            "accessory": "PhilipsAndroidTV"
}

homebridge 1.3.4
homebridge-philips-android-tv v0.4.15

**Comment by try-and-error-and-repeat** [comment]
The problem is that with the last firmware update your apiuser and apipassword are invalid. try to pair again with the script and change the Homebridge config and it should work again

**Comment by Tabek-pl** [comment]
@try-and-error-and-repeat yes, it helps! Thanks :)

**Comment by konradknitter** [comment]
This log should no longer happen. Added to readme that after update repairing might be required. Thanks for catching this.
