### ISSUE TITLE
0.10.0 | "Apps" are not exposed to Homekit anymore

### ISSUE THREAD

**Issue by jonas240** [konradknitter/homebridge-philips-android-tv#34]
**Describe The Bug:**

Hi,
I just upgraded to 0.10.0 and reconfigured my TV to the platform configuration (manuel as described in the last comment of #25). It workes so far, however only channels are exposed in homekit. Apps are shown in the homebridge logs (HOOBS for me) as configured but not exposed.

**To Reproduce:**

I reinstalled the plugin and pasted the example configuartion (with my credentials) into the platforms part of the JASON. Further I deleted the TV in Homekit and added it again.

**Expected behavior:**

Apps like Netflix are exposed.

**Logs:**
Currently TV showes Netflix App:
```
//configuration:
...
apps: [ 'Netflix', 'YouTube', 'Disney+', 'Prime Video', 'Plex', 'TV' ],
...

//log:
[PhilipsAndroidTV] [TV] Current application has been changed to NA.
```

**Plugin Config:**

```json
    "platforms": [
        {
            "debug": false,
            "configVersion": 1,
            "tvs": [
                {
                    "ip": "***",
                    "mac": "***",
                    "name": "TV",
                    "apiUser": "***",
                    "apiPass": "***",
                    "apiVersion": 6,
                    "alternativePlayPause": true,
                    "dedicatedMuteSwitch": false,
                    "dedicatedVolumeLightbulb": false,
                    "apps": [
                        "Netflix",
                        "YouTube",
                        "Disney+",
                        "Prime Video",
                        "Plex",
                        "TV"
                    ],
                    "channels": {
                        "useFavorites": false,
                        "favoriteListId": "1",
                        "includeAll": false,
                        "channels": [
                            "Das Erste HD",
                            "ZDF HD",
                            "SAT.1",
                            "RTL",
                            "ProSieben",
                            "WELT",
                            "N24 Doku"
                        ]
                    }
                }
            ],
            "platform": "PhilipsAndroidTV",
            "plugin_map": {
                "plugin_name": "homebridge-philips-android-tv"
            }
        },
```

**Screenshots:**

![IMG_0306](https://user-images.githubusercontent.com/68380809/120660220-68094880-c487-11eb-889a-a2d7f3e80645.PNG)
![IMG_0307](https://user-images.githubusercontent.com/68380809/120660242-6c356600-c487-11eb-9f08-8786ac833d96.PNG)

**Environment:**

* **Plugin Version**: 0.10.0
* **Homebridge Version**:  1.3.3
* **Node.js Version**:  14.17.0
* **NPM Version**:  3.3.5
* **Operating System**: Raspbian

**Comment by konradknitter** [comment]
I found the issue. 0.10.1 fixes that.

**Comment by jonas240** [comment]
Thanks for the quick fix! Homebridge/HOOBS doesn't show the update yet. I'll get back to this when it does.

**Comment by jonas240** [comment]
Apps are now inputs, but HomeKit is not able to change the app. Channels still work fine.

That's the log if I try for example YouTube:

```4.6.2021, 14:56:34 (node:27820) UnhandledPromiseRejectionWarning: TypeError: this.apps is not iterable
4.6.2021, 14:56:34 at PhilipsTVAccessory.launchActivity (/home/hoobs/.hoobs/node_modules/homebridge-philips-android-tv/src/PhilipsTVAccessory.ts:447:45)
4.6.2021, 14:56:34 at ActiveIdentifier.emit (events.js:376:20)
4.6.2021, 14:56:34 at /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/src/lib/Characteristic.ts:1630:16
4.6.2021, 14:56:34 at new Promise (<anonymous>)
4.6.2021, 14:56:34 at ActiveIdentifier.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/src/lib/Characteristic.ts:1628:14)
4.6.2021, 14:56:34 at step (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/tslib/tslib.js:143:27)
4.6.2021, 14:56:34 at Object.next (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/tslib/tslib.js:124:57)
4.6.2021, 14:56:34 at /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/tslib/tslib.js:117:75
4.6.2021, 14:56:34 at new Promise (<anonymous>)
4.6.2021, 14:56:34 at Object.__awaiter (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/tslib/tslib.js:113:16)
4.6.2021, 14:56:34 at ActiveIdentifier.Characteristic.handleSetRequest (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/Characteristic.js:791:24)
4.6.2021, 14:56:34 at Accessory.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/src/lib/Accessory.ts:1741:29)
4.6.2021, 14:56:34 at step (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/tslib/tslib.js:143:27)
4.6.2021, 14:56:34 at Object.next (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/tslib/tslib.js:124:57)
4.6.2021, 14:56:34 at /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/tslib/tslib.js:117:75
4.6.2021, 14:56:34 at new Promise (<anonymous>)
4.6.2021, 14:56:34 (node:27820) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
4.6.2021, 14:56:37 [TV 5688@Active Identifier] The write handler for the characteristic 'Active Identifier' on the accessory 'TV 5688' was slow to respond!
4.6.2021, 14:56:43 [TV 5688@Active Identifier] The write handler for the characteristic 'Active Identifier' on the accessory 'TV 5688' didn't respond at all!. Please check that you properly call the callback!```

**Comment by konradknitter** [comment]
Fixed, and callback called faster - in 0.10.6. Sorry for that.
